### ISSUE TITLE
TODO LIST

### ISSUE THREAD

**Issue by azzgo** [ThoughtWorks-Chengdu-DevOps-Club/viff-client-java#3]
- [ ] configure of webdriver
- [ ] add async upload screenshot
- [ ] viff compare function
- [x] mock
- [ ] maven
